ALTER TABLE PROCURATOR ADD AGE INT;
ALTER TABLE PROCURATOR ADD SEX VARCHAR(10);
ALTER TABLE PROCURATOR ADD BIRTHDAY DATE;
ALTER TABLE PROCURATOR ADD ID_NUMBER INT;
ALTER TABLE PROCURATOR ADD EXPERIENCE INT;