ALTER TABLE PROCURATOR ADD CONSTRAINT CK_AGE CHECK(AGE>18);
ALTER TABLE PROCURATOR ADD CONSTRAINT CK_SEX CHECK(SEX IN('男','女'));
ALTER TABLE PROCURATOR ADD CONSTRAINT CK_EXPERIENCE CHECK(EXPERIENCE>0);